### ISSUE TITLE
LAB_13_Azure Monitor.md - Translation recommendation

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.zh-cn#4]
# Module: 00
#### Step: 05

A QA pass recommended the following translation change:

输入：Install-Module -Name Az.Compute -Force -RequiredVersion 4.23.0
输入：pwsh
输入：Get-Module -Name Az.Compute

'Type' should be translated to '输入' instead of ‘类型'

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfile](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtDaGluZXNlIChTaW1wbGlmaWVkKTwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEZpbGUgUmVmZXJlbmNlO0VxdWFsOzUwMzM3Lkluc3RydWN0aW9ucy5MYWJzLkxBQl8xM19BenVyZSBNb25pdG9yLm1kPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d) is at PHO so blocked as it must be at HB

**Comment by chriscarty00** [comment]
Discussed with the PM - update made to the older HB locfiles and this will seed the TM when handedback
